[33mWARNING[0m:  [11-07-2024 22:54:29] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[32mINFO[0m:     [11-07-2024 22:54:30] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [11-07-2024 22:54:30] Starting component System
[36mDEBUG[0m:    [11-07-2024 22:54:30] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [11-07-2024 22:54:30] Starting component SqliteDB
[36mDEBUG[0m:    [11-07-2024 22:54:30] Starting component QuotaEnforcer
[36mDEBUG[0m:    [11-07-2024 22:54:30] Starting component Posthog
[36mDEBUG[0m:    [11-07-2024 22:54:30] Starting component LocalSegmentManager
[36mDEBUG[0m:    [11-07-2024 22:54:30] Starting component SegmentAPI
[32mINFO[0m:     [11-07-2024 22:54:30] Started server process [[36m10430[0m]
[32mINFO[0m:     [11-07-2024 22:54:30] Waiting for application startup.
[32mINFO[0m:     [11-07-2024 22:54:30] Application startup complete.
[32mINFO[0m:     [11-07-2024 22:54:30] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [11-07-2024 22:55:01] Shutting down
[32mINFO[0m:     [11-07-2024 22:55:01] Waiting for application shutdown.
[36mDEBUG[0m:    [11-07-2024 22:55:01] Stopping component System
[36mDEBUG[0m:    [11-07-2024 22:55:01] Stopping component SegmentAPI
[36mDEBUG[0m:    [11-07-2024 22:55:01] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [11-07-2024 22:55:01] Stopping component Posthog
[36mDEBUG[0m:    [11-07-2024 22:55:01] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [11-07-2024 22:55:01] Stopping component SqliteDB
[36mDEBUG[0m:    [11-07-2024 22:55:01] Stopping component OpenTelemetryClient
[32mINFO[0m:     [11-07-2024 22:55:01] Application shutdown complete.
[32mINFO[0m:     [11-07-2024 22:55:01] Finished server process [[36m10430[0m]
[33mWARNING[0m:  [11-07-2024 22:55:13] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[32mINFO[0m:     [11-07-2024 22:55:13] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [11-07-2024 22:55:13] Starting component System
[36mDEBUG[0m:    [11-07-2024 22:55:13] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [11-07-2024 22:55:13] Starting component SqliteDB
[36mDEBUG[0m:    [11-07-2024 22:55:13] Starting component QuotaEnforcer
[36mDEBUG[0m:    [11-07-2024 22:55:13] Starting component Posthog
[36mDEBUG[0m:    [11-07-2024 22:55:13] Starting component LocalSegmentManager
[36mDEBUG[0m:    [11-07-2024 22:55:13] Starting component SegmentAPI
[32mINFO[0m:     [11-07-2024 22:55:13] Started server process [[36m10597[0m]
[32mINFO[0m:     [11-07-2024 22:55:13] Waiting for application startup.
[32mINFO[0m:     [11-07-2024 22:55:13] Application startup complete.
[32mINFO[0m:     [11-07-2024 22:55:13] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [11-07-2024 22:55:47] Shutting down
[32mINFO[0m:     [11-07-2024 22:55:47] Waiting for application shutdown.
[36mDEBUG[0m:    [11-07-2024 22:55:47] Stopping component System
[36mDEBUG[0m:    [11-07-2024 22:55:47] Stopping component SegmentAPI
[36mDEBUG[0m:    [11-07-2024 22:55:47] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [11-07-2024 22:55:47] Stopping component Posthog
[36mDEBUG[0m:    [11-07-2024 22:55:47] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [11-07-2024 22:55:47] Stopping component SqliteDB
[36mDEBUG[0m:    [11-07-2024 22:55:47] Stopping component OpenTelemetryClient
[32mINFO[0m:     [11-07-2024 22:55:47] Application shutdown complete.
[32mINFO[0m:     [11-07-2024 22:55:47] Finished server process [[36m10597[0m]
WARNING:  [11-07-2024 23:14:51] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:14:51] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:14:51] Starting component System
DEBUG:    [11-07-2024 23:14:51] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:14:51] Starting component SqliteDB
DEBUG:    [11-07-2024 23:14:52] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:14:52] Starting component Posthog
DEBUG:    [11-07-2024 23:14:52] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:14:52] Starting component SegmentAPI
INFO:     [11-07-2024 23:14:52] Started server process [13870]
INFO:     [11-07-2024 23:14:52] Waiting for application startup.
INFO:     [11-07-2024 23:14:52] Application startup complete.
INFO:     [11-07-2024 23:14:52] Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     [11-07-2024 23:15:26] Shutting down
INFO:     [11-07-2024 23:15:26] Waiting for application shutdown.
DEBUG:    [11-07-2024 23:15:26] Stopping component System
DEBUG:    [11-07-2024 23:15:26] Stopping component SegmentAPI
DEBUG:    [11-07-2024 23:15:26] Stopping component LocalSegmentManager
DEBUG:    [11-07-2024 23:15:26] Stopping component Posthog
DEBUG:    [11-07-2024 23:15:26] Stopping component QuotaEnforcer
DEBUG:    [11-07-2024 23:15:26] Stopping component SqliteDB
DEBUG:    [11-07-2024 23:15:26] Stopping component OpenTelemetryClient
INFO:     [11-07-2024 23:15:26] Application shutdown complete.
INFO:     [11-07-2024 23:15:26] Finished server process [13870]
[33mWARNING[0m:  [11-07-2024 23:15:36] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[32mINFO[0m:     [11-07-2024 23:15:37] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [11-07-2024 23:15:37] Starting component System
[36mDEBUG[0m:    [11-07-2024 23:15:37] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [11-07-2024 23:15:37] Starting component SqliteDB
[36mDEBUG[0m:    [11-07-2024 23:15:37] Starting component QuotaEnforcer
[36mDEBUG[0m:    [11-07-2024 23:15:37] Starting component Posthog
[36mDEBUG[0m:    [11-07-2024 23:15:37] Starting component LocalSegmentManager
[36mDEBUG[0m:    [11-07-2024 23:15:37] Starting component SegmentAPI
[32mINFO[0m:     [11-07-2024 23:15:37] Started server process [[36m13897[0m]
[32mINFO[0m:     [11-07-2024 23:15:37] Waiting for application startup.
[32mINFO[0m:     [11-07-2024 23:15:37] Application startup complete.
[32mINFO[0m:     [11-07-2024 23:15:37] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [11-07-2024 23:15:40] Shutting down
[32mINFO[0m:     [11-07-2024 23:15:40] Waiting for application shutdown.
[36mDEBUG[0m:    [11-07-2024 23:15:40] Stopping component System
[36mDEBUG[0m:    [11-07-2024 23:15:40] Stopping component SegmentAPI
[36mDEBUG[0m:    [11-07-2024 23:15:40] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [11-07-2024 23:15:40] Stopping component Posthog
[36mDEBUG[0m:    [11-07-2024 23:15:40] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [11-07-2024 23:15:40] Stopping component SqliteDB
[36mDEBUG[0m:    [11-07-2024 23:15:40] Stopping component OpenTelemetryClient
[32mINFO[0m:     [11-07-2024 23:15:40] Application shutdown complete.
[32mINFO[0m:     [11-07-2024 23:15:40] Finished server process [[36m13897[0m]
WARNING:  [11-07-2024 23:15:43] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:15:43] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:15:43] Starting component System
DEBUG:    [11-07-2024 23:15:43] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:15:43] Starting component SqliteDB
DEBUG:    [11-07-2024 23:15:43] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:15:43] Starting component Posthog
DEBUG:    [11-07-2024 23:15:43] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:15:43] Starting component SegmentAPI
INFO:     [11-07-2024 23:15:43] Started server process [13914]
INFO:     [11-07-2024 23:15:43] Waiting for application startup.
INFO:     [11-07-2024 23:15:43] Application startup complete.
INFO:     [11-07-2024 23:15:43] Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     [11-07-2024 23:15:52] Shutting down
INFO:     [11-07-2024 23:15:52] Waiting for application shutdown.
DEBUG:    [11-07-2024 23:15:52] Stopping component System
DEBUG:    [11-07-2024 23:15:52] Stopping component SegmentAPI
DEBUG:    [11-07-2024 23:15:52] Stopping component LocalSegmentManager
DEBUG:    [11-07-2024 23:15:52] Stopping component Posthog
DEBUG:    [11-07-2024 23:15:52] Stopping component QuotaEnforcer
DEBUG:    [11-07-2024 23:15:52] Stopping component SqliteDB
DEBUG:    [11-07-2024 23:15:52] Stopping component OpenTelemetryClient
INFO:     [11-07-2024 23:15:52] Application shutdown complete.
INFO:     [11-07-2024 23:15:52] Finished server process [13914]
[33mWARNING[0m:  [11-07-2024 23:16:03] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[32mINFO[0m:     [11-07-2024 23:16:03] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [11-07-2024 23:16:03] Starting component System
[36mDEBUG[0m:    [11-07-2024 23:16:03] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [11-07-2024 23:16:03] Starting component SqliteDB
[36mDEBUG[0m:    [11-07-2024 23:16:03] Starting component QuotaEnforcer
[36mDEBUG[0m:    [11-07-2024 23:16:03] Starting component Posthog
[36mDEBUG[0m:    [11-07-2024 23:16:03] Starting component LocalSegmentManager
[36mDEBUG[0m:    [11-07-2024 23:16:03] Starting component SegmentAPI
[32mINFO[0m:     [11-07-2024 23:16:03] Started server process [[36m13967[0m]
[32mINFO[0m:     [11-07-2024 23:16:03] Waiting for application startup.
[32mINFO[0m:     [11-07-2024 23:16:03] Application startup complete.
[32mINFO[0m:     [11-07-2024 23:16:03] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [11-07-2024 23:16:04] Shutting down
[32mINFO[0m:     [11-07-2024 23:16:04] Waiting for application shutdown.
[36mDEBUG[0m:    [11-07-2024 23:16:04] Stopping component System
[36mDEBUG[0m:    [11-07-2024 23:16:04] Stopping component SegmentAPI
[36mDEBUG[0m:    [11-07-2024 23:16:04] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [11-07-2024 23:16:04] Stopping component Posthog
[36mDEBUG[0m:    [11-07-2024 23:16:04] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [11-07-2024 23:16:04] Stopping component SqliteDB
[36mDEBUG[0m:    [11-07-2024 23:16:04] Stopping component OpenTelemetryClient
[32mINFO[0m:     [11-07-2024 23:16:04] Application shutdown complete.
[32mINFO[0m:     [11-07-2024 23:16:04] Finished server process [[36m13967[0m]
WARNING:  [11-07-2024 23:16:09] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:16:09] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:16:09] Starting component System
DEBUG:    [11-07-2024 23:16:09] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:16:09] Starting component SqliteDB
DEBUG:    [11-07-2024 23:16:09] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:16:09] Starting component Posthog
DEBUG:    [11-07-2024 23:16:09] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:16:09] Starting component SegmentAPI
INFO:     [11-07-2024 23:16:09] Started server process [14014]
INFO:     [11-07-2024 23:16:09] Waiting for application startup.
INFO:     [11-07-2024 23:16:09] Application startup complete.
INFO:     [11-07-2024 23:16:09] Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     [11-07-2024 23:16:42] Shutting down
INFO:     [11-07-2024 23:16:42] Waiting for application shutdown.
DEBUG:    [11-07-2024 23:16:42] Stopping component System
DEBUG:    [11-07-2024 23:16:42] Stopping component SegmentAPI
DEBUG:    [11-07-2024 23:16:42] Stopping component LocalSegmentManager
DEBUG:    [11-07-2024 23:16:42] Stopping component Posthog
DEBUG:    [11-07-2024 23:16:42] Stopping component QuotaEnforcer
DEBUG:    [11-07-2024 23:16:42] Stopping component SqliteDB
DEBUG:    [11-07-2024 23:16:42] Stopping component OpenTelemetryClient
INFO:     [11-07-2024 23:16:42] Application shutdown complete.
INFO:     [11-07-2024 23:16:42] Finished server process [14014]
WARNING:  [11-07-2024 23:16:46] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:16:46] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:16:46] Starting component System
DEBUG:    [11-07-2024 23:16:46] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:16:46] Starting component SqliteDB
DEBUG:    [11-07-2024 23:16:46] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:16:46] Starting component Posthog
DEBUG:    [11-07-2024 23:16:46] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:16:46] Starting component SegmentAPI
INFO:     [11-07-2024 23:16:46] Started server process [14102]
INFO:     [11-07-2024 23:16:46] Waiting for application startup.
INFO:     [11-07-2024 23:16:46] Application startup complete.
INFO:     [11-07-2024 23:16:46] Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     [11-07-2024 23:17:50] Shutting down
INFO:     [11-07-2024 23:17:51] Waiting for application shutdown.
DEBUG:    [11-07-2024 23:17:51] Stopping component System
DEBUG:    [11-07-2024 23:17:51] Stopping component SegmentAPI
DEBUG:    [11-07-2024 23:17:51] Stopping component LocalSegmentManager
DEBUG:    [11-07-2024 23:17:51] Stopping component Posthog
DEBUG:    [11-07-2024 23:17:51] Stopping component QuotaEnforcer
DEBUG:    [11-07-2024 23:17:51] Stopping component SqliteDB
DEBUG:    [11-07-2024 23:17:51] Stopping component OpenTelemetryClient
INFO:     [11-07-2024 23:17:51] Application shutdown complete.
INFO:     [11-07-2024 23:17:51] Finished server process [14102]
WARNING:  [11-07-2024 23:17:54] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:17:54] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:17:54] Starting component System
DEBUG:    [11-07-2024 23:17:54] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:17:54] Starting component SqliteDB
DEBUG:    [11-07-2024 23:17:54] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:17:54] Starting component Posthog
DEBUG:    [11-07-2024 23:17:54] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:17:54] Starting component SegmentAPI
INFO:     [11-07-2024 23:17:54] Started server process [14197]
INFO:     [11-07-2024 23:17:54] Waiting for application startup.
INFO:     [11-07-2024 23:17:54] Application startup complete.
INFO:     [11-07-2024 23:17:54] Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     [11-07-2024 23:18:45] ::1:64583 - "GET /api/v1/version HTTP/1.1" 200
INFO:     [11-07-2024 23:18:45] ::1:64583 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
INFO:     [11-07-2024 23:18:45] ::1:64583 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
INFO:     [11-07-2024 23:18:45] ::1:64583 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
ERROR:    [11-07-2024 23:18:45] Collection test_collection does not exist.
Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 105, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 118, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 76, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 90, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 637, in get_collection
    await to_thread.run_sync(
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/api/segment.py", line 251, in get_collection
    raise ValueError(f"Collection {name} does not exist.")
ValueError: Collection test_collection does not exist.
INFO:     [11-07-2024 23:18:45] ::1:64583 - "GET /api/v1/collections/test_collection?database=default_database&tenant=default_tenant HTTP/1.1" 500
INFO:     [11-07-2024 23:18:45] ::1:64583 - "POST /api/v1/collections HTTP/1.1" 200
WARNING:  [11-07-2024 23:18:46] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:18:46] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:18:46] Starting component System
DEBUG:    [11-07-2024 23:18:46] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:18:46] Starting component SqliteDB
DEBUG:    [11-07-2024 23:18:46] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:18:46] Starting component Posthog
DEBUG:    [11-07-2024 23:18:46] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:18:46] Starting component SegmentAPI
INFO:     [11-07-2024 23:18:46] Started server process [14377]
INFO:     [11-07-2024 23:18:46] Waiting for application startup.
INFO:     [11-07-2024 23:18:46] Application startup complete.
ERROR:    [11-07-2024 23:18:46] [Errno 48] error while attempting to bind on address ('::1', 8000, 0, 0): address already in use
INFO:     [11-07-2024 23:18:46] Waiting for application shutdown.
DEBUG:    [11-07-2024 23:18:46] Stopping component System
DEBUG:    [11-07-2024 23:18:46] Stopping component SegmentAPI
DEBUG:    [11-07-2024 23:18:46] Stopping component LocalSegmentManager
DEBUG:    [11-07-2024 23:18:46] Stopping component Posthog
DEBUG:    [11-07-2024 23:18:46] Stopping component QuotaEnforcer
DEBUG:    [11-07-2024 23:18:46] Stopping component SqliteDB
DEBUG:    [11-07-2024 23:18:46] Stopping component OpenTelemetryClient
INFO:     [11-07-2024 23:18:46] Application shutdown complete.
INFO:     [11-07-2024 23:23:31] ::1:64634 - "GET /api/v1/version HTTP/1.1" 200
INFO:     [11-07-2024 23:23:31] ::1:64634 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
INFO:     [11-07-2024 23:23:31] ::1:64634 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
INFO:     [11-07-2024 23:23:31] ::1:64634 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
INFO:     [11-07-2024 23:23:31] ::1:64634 - "GET /api/v1/collections/test_collection?database=default_database&tenant=default_tenant HTTP/1.1" 200
WARNING:  [11-07-2024 23:23:32] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:23:32] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:23:32] Starting component System
DEBUG:    [11-07-2024 23:23:32] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:23:32] Starting component SqliteDB
DEBUG:    [11-07-2024 23:23:32] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:23:32] Starting component Posthog
DEBUG:    [11-07-2024 23:23:32] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:23:32] Starting component SegmentAPI
INFO:     [11-07-2024 23:23:32] Started server process [14553]
INFO:     [11-07-2024 23:23:32] Waiting for application startup.
INFO:     [11-07-2024 23:23:32] Application startup complete.
ERROR:    [11-07-2024 23:23:32] [Errno 48] error while attempting to bind on address ('::1', 8000, 0, 0): address already in use
INFO:     [11-07-2024 23:23:32] Waiting for application shutdown.
DEBUG:    [11-07-2024 23:23:32] Stopping component System
DEBUG:    [11-07-2024 23:23:32] Stopping component SegmentAPI
DEBUG:    [11-07-2024 23:23:32] Stopping component LocalSegmentManager
DEBUG:    [11-07-2024 23:23:32] Stopping component Posthog
DEBUG:    [11-07-2024 23:23:32] Stopping component QuotaEnforcer
DEBUG:    [11-07-2024 23:23:32] Stopping component SqliteDB
DEBUG:    [11-07-2024 23:23:32] Stopping component OpenTelemetryClient
INFO:     [11-07-2024 23:23:32] Application shutdown complete.
DEBUG:    [11-07-2024 23:23:32] Starting component PersistentLocalHnswSegment
INFO:     [11-07-2024 23:23:32] ::1:64634 - "POST /api/v1/collections/3a0abe6f-78c9-4073-b786-507ef15de355/add HTTP/1.1" 201
INFO:     [11-07-2024 23:23:32] ::1:64634 - "GET /api/v1/collections/3a0abe6f-78c9-4073-b786-507ef15de355/count HTTP/1.1" 200
WARNING:  [11-07-2024 23:23:32] Number of requested results 5 is greater than number of elements in index 2, updating n_results = 2
INFO:     [11-07-2024 23:23:32] ::1:64634 - "POST /api/v1/collections/3a0abe6f-78c9-4073-b786-507ef15de355/query HTTP/1.1" 200
INFO:     [11-07-2024 23:31:48] ::1:64664 - "GET /api/v1/version HTTP/1.1" 200
INFO:     [11-07-2024 23:31:48] ::1:64664 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
INFO:     [11-07-2024 23:31:48] ::1:64664 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
INFO:     [11-07-2024 23:31:48] ::1:64664 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
INFO:     [11-07-2024 23:31:48] ::1:64664 - "GET /api/v1/collections/slugiscool99/pls?database=default_database&tenant=default_tenant HTTP/1.1" 404
ERROR:    [11-07-2024 23:31:48] Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got slugiscool99/pls
Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 105, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 118, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 76, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 90, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 601, in create_collection
    await to_thread.run_sync(
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 590, in process_create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/api/segment.py", line 160, in create_collection
    check_index_name(name)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/api/segment.py", line 75, in check_index_name
    raise ValueError(msg)
ValueError: Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got slugiscool99/pls
INFO:     [11-07-2024 23:31:48] ::1:64664 - "POST /api/v1/collections HTTP/1.1" 500
WARNING:  [11-07-2024 23:31:48] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:31:48] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:31:48] Starting component System
DEBUG:    [11-07-2024 23:31:48] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:31:48] Starting component SqliteDB
DEBUG:    [11-07-2024 23:31:48] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:31:48] Starting component Posthog
DEBUG:    [11-07-2024 23:31:48] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:31:48] Starting component SegmentAPI
INFO:     [11-07-2024 23:31:48] Started server process [15161]
INFO:     [11-07-2024 23:31:48] Waiting for application startup.
INFO:     [11-07-2024 23:31:48] Application startup complete.
ERROR:    [11-07-2024 23:31:48] [Errno 48] error while attempting to bind on address ('::1', 8000, 0, 0): address already in use
INFO:     [11-07-2024 23:31:48] Waiting for application shutdown.
DEBUG:    [11-07-2024 23:31:48] Stopping component System
DEBUG:    [11-07-2024 23:31:48] Stopping component SegmentAPI
DEBUG:    [11-07-2024 23:31:48] Stopping component LocalSegmentManager
DEBUG:    [11-07-2024 23:31:48] Stopping component Posthog
DEBUG:    [11-07-2024 23:31:48] Stopping component QuotaEnforcer
DEBUG:    [11-07-2024 23:31:48] Stopping component SqliteDB
DEBUG:    [11-07-2024 23:31:48] Stopping component OpenTelemetryClient
INFO:     [11-07-2024 23:31:48] Application shutdown complete.
INFO:     [11-07-2024 23:31:53] ::1:64669 - "GET /api/v1/version HTTP/1.1" 200
INFO:     [11-07-2024 23:31:53] ::1:64669 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
INFO:     [11-07-2024 23:31:53] ::1:64669 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
INFO:     [11-07-2024 23:31:53] ::1:64669 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
INFO:     [11-07-2024 23:31:53] ::1:64669 - "GET /api/v1/collections/slugiscool99/pls?database=default_database&tenant=default_tenant HTTP/1.1" 404
ERROR:    [11-07-2024 23:31:53] Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got slugiscool99/pls
Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 105, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 118, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 76, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 90, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 601, in create_collection
    await to_thread.run_sync(
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 590, in process_create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/api/segment.py", line 160, in create_collection
    check_index_name(name)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/api/segment.py", line 75, in check_index_name
    raise ValueError(msg)
ValueError: Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got slugiscool99/pls
INFO:     [11-07-2024 23:31:53] ::1:64669 - "POST /api/v1/collections HTTP/1.1" 500
WARNING:  [11-07-2024 23:31:53] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:31:53] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:31:53] Starting component System
DEBUG:    [11-07-2024 23:31:53] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:31:53] Starting component SqliteDB
DEBUG:    [11-07-2024 23:31:53] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:31:53] Starting component Posthog
DEBUG:    [11-07-2024 23:31:53] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:31:53] Starting component SegmentAPI
INFO:     [11-07-2024 23:31:53] Started server process [15183]
INFO:     [11-07-2024 23:31:53] Waiting for application startup.
INFO:     [11-07-2024 23:31:53] Application startup complete.
ERROR:    [11-07-2024 23:31:53] [Errno 48] error while attempting to bind on address ('::1', 8000, 0, 0): address already in use
INFO:     [11-07-2024 23:31:53] Waiting for application shutdown.
DEBUG:    [11-07-2024 23:31:53] Stopping component System
DEBUG:    [11-07-2024 23:31:53] Stopping component SegmentAPI
DEBUG:    [11-07-2024 23:31:53] Stopping component LocalSegmentManager
DEBUG:    [11-07-2024 23:31:53] Stopping component Posthog
DEBUG:    [11-07-2024 23:31:53] Stopping component QuotaEnforcer
DEBUG:    [11-07-2024 23:31:53] Stopping component SqliteDB
DEBUG:    [11-07-2024 23:31:53] Stopping component OpenTelemetryClient
INFO:     [11-07-2024 23:31:53] Application shutdown complete.
[33mWARNING[0m:  [11-07-2024 23:32:04] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[32mINFO[0m:     [11-07-2024 23:32:04] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [11-07-2024 23:32:04] Starting component System
[36mDEBUG[0m:    [11-07-2024 23:32:04] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [11-07-2024 23:32:04] Starting component SqliteDB
[36mDEBUG[0m:    [11-07-2024 23:32:04] Starting component QuotaEnforcer
[36mDEBUG[0m:    [11-07-2024 23:32:04] Starting component Posthog
[36mDEBUG[0m:    [11-07-2024 23:32:04] Starting component LocalSegmentManager
[36mDEBUG[0m:    [11-07-2024 23:32:04] Starting component SegmentAPI
[32mINFO[0m:     [11-07-2024 23:32:04] Started server process [[36m15198[0m]
[32mINFO[0m:     [11-07-2024 23:32:04] Waiting for application startup.
[32mINFO[0m:     [11-07-2024 23:32:04] Application startup complete.
[31mERROR[0m:    [11-07-2024 23:32:04] [Errno 48] error while attempting to bind on address ('::1', 8000, 0, 0): address already in use
[32mINFO[0m:     [11-07-2024 23:32:04] Waiting for application shutdown.
[36mDEBUG[0m:    [11-07-2024 23:32:04] Stopping component System
[36mDEBUG[0m:    [11-07-2024 23:32:04] Stopping component SegmentAPI
[36mDEBUG[0m:    [11-07-2024 23:32:04] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [11-07-2024 23:32:04] Stopping component Posthog
[36mDEBUG[0m:    [11-07-2024 23:32:04] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [11-07-2024 23:32:04] Stopping component SqliteDB
[36mDEBUG[0m:    [11-07-2024 23:32:04] Stopping component OpenTelemetryClient
[32mINFO[0m:     [11-07-2024 23:32:04] Application shutdown complete.
INFO:     [11-07-2024 23:32:37] ::1:64676 - "GET /api/v1/version HTTP/1.1" 200
INFO:     [11-07-2024 23:32:37] ::1:64676 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
INFO:     [11-07-2024 23:32:37] ::1:64676 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
INFO:     [11-07-2024 23:32:37] ::1:64676 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
INFO:     [11-07-2024 23:32:37] ::1:64676 - "GET /api/v1/collections/slugiscool99/pls?database=default_database&tenant=default_tenant HTTP/1.1" 404
ERROR:    [11-07-2024 23:32:37] Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got slugiscool99/pls
Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 105, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 118, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 76, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 90, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 601, in create_collection
    await to_thread.run_sync(
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 590, in process_create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/api/segment.py", line 160, in create_collection
    check_index_name(name)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/api/segment.py", line 75, in check_index_name
    raise ValueError(msg)
ValueError: Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got slugiscool99/pls
INFO:     [11-07-2024 23:32:37] ::1:64676 - "POST /api/v1/collections HTTP/1.1" 500
WARNING:  [11-07-2024 23:32:38] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:32:38] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:32:38] Starting component System
DEBUG:    [11-07-2024 23:32:38] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:32:38] Starting component SqliteDB
DEBUG:    [11-07-2024 23:32:38] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:32:38] Starting component Posthog
DEBUG:    [11-07-2024 23:32:38] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:32:38] Starting component SegmentAPI
INFO:     [11-07-2024 23:32:38] Started server process [15233]
INFO:     [11-07-2024 23:32:38] Waiting for application startup.
INFO:     [11-07-2024 23:32:38] Application startup complete.
ERROR:    [11-07-2024 23:32:38] [Errno 48] error while attempting to bind on address ('::1', 8000, 0, 0): address already in use
INFO:     [11-07-2024 23:32:38] Waiting for application shutdown.
DEBUG:    [11-07-2024 23:32:38] Stopping component System
DEBUG:    [11-07-2024 23:32:38] Stopping component SegmentAPI
DEBUG:    [11-07-2024 23:32:38] Stopping component LocalSegmentManager
DEBUG:    [11-07-2024 23:32:38] Stopping component Posthog
DEBUG:    [11-07-2024 23:32:38] Stopping component QuotaEnforcer
DEBUG:    [11-07-2024 23:32:38] Stopping component SqliteDB
DEBUG:    [11-07-2024 23:32:38] Stopping component OpenTelemetryClient
INFO:     [11-07-2024 23:32:38] Application shutdown complete.
[33mWARNING[0m:  [11-07-2024 23:32:47] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[32mINFO[0m:     [11-07-2024 23:32:47] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [11-07-2024 23:32:47] Starting component System
[36mDEBUG[0m:    [11-07-2024 23:32:47] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [11-07-2024 23:32:47] Starting component SqliteDB
[36mDEBUG[0m:    [11-07-2024 23:32:47] Starting component QuotaEnforcer
[36mDEBUG[0m:    [11-07-2024 23:32:47] Starting component Posthog
[36mDEBUG[0m:    [11-07-2024 23:32:47] Starting component LocalSegmentManager
[36mDEBUG[0m:    [11-07-2024 23:32:47] Starting component SegmentAPI
[32mINFO[0m:     [11-07-2024 23:32:47] Started server process [[36m15252[0m]
[32mINFO[0m:     [11-07-2024 23:32:47] Waiting for application startup.
[32mINFO[0m:     [11-07-2024 23:32:47] Application startup complete.
[31mERROR[0m:    [11-07-2024 23:32:47] [Errno 48] error while attempting to bind on address ('::1', 8000, 0, 0): address already in use
[32mINFO[0m:     [11-07-2024 23:32:47] Waiting for application shutdown.
[36mDEBUG[0m:    [11-07-2024 23:32:47] Stopping component System
[36mDEBUG[0m:    [11-07-2024 23:32:47] Stopping component SegmentAPI
[36mDEBUG[0m:    [11-07-2024 23:32:47] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [11-07-2024 23:32:47] Stopping component Posthog
[36mDEBUG[0m:    [11-07-2024 23:32:47] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [11-07-2024 23:32:47] Stopping component SqliteDB
[36mDEBUG[0m:    [11-07-2024 23:32:47] Stopping component OpenTelemetryClient
[32mINFO[0m:     [11-07-2024 23:32:47] Application shutdown complete.
INFO:     [11-07-2024 23:36:37] ::1:64699 - "GET /api/v1/version HTTP/1.1" 200
INFO:     [11-07-2024 23:36:37] ::1:64699 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
INFO:     [11-07-2024 23:36:37] ::1:64699 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
INFO:     [11-07-2024 23:36:37] ::1:64699 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
INFO:     [11-07-2024 23:36:37] ::1:64699 - "GET /api/v1/collections/slugiscool99/pls?database=default_database&tenant=default_tenant HTTP/1.1" 404
ERROR:    [11-07-2024 23:36:37] Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got slugiscool99/pls
Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 105, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 118, in receive
    return receiver.item
           ^^^^^^^^^^^^^
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/streams/memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 76, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 90, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 601, in create_collection
    await to_thread.run_sync(
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 590, in process_create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/api/segment.py", line 160, in create_collection
    check_index_name(name)
  File "/Users/adam/.local/pipx/venvs/chromadb/lib/python3.12/site-packages/chromadb/api/segment.py", line 75, in check_index_name
    raise ValueError(msg)
ValueError: Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got slugiscool99/pls
INFO:     [11-07-2024 23:36:37] ::1:64699 - "POST /api/v1/collections HTTP/1.1" 500
WARNING:  [11-07-2024 23:38:33] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:38:33] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:38:33] Starting component System
DEBUG:    [11-07-2024 23:38:33] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:38:33] Starting component SqliteDB
DEBUG:    [11-07-2024 23:38:33] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:38:33] Starting component Posthog
DEBUG:    [11-07-2024 23:38:33] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:38:33] Starting component SegmentAPI
INFO:     [11-07-2024 23:38:34] Started server process [15865]
INFO:     [11-07-2024 23:38:34] Waiting for application startup.
INFO:     [11-07-2024 23:38:34] Application startup complete.
INFO:     [11-07-2024 23:38:34] Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     [11-07-2024 23:39:38] Shutting down
INFO:     [11-07-2024 23:39:38] Waiting for application shutdown.
DEBUG:    [11-07-2024 23:39:38] Stopping component System
DEBUG:    [11-07-2024 23:39:38] Stopping component SegmentAPI
DEBUG:    [11-07-2024 23:39:38] Stopping component LocalSegmentManager
DEBUG:    [11-07-2024 23:39:38] Stopping component Posthog
DEBUG:    [11-07-2024 23:39:38] Stopping component QuotaEnforcer
DEBUG:    [11-07-2024 23:39:38] Stopping component SqliteDB
DEBUG:    [11-07-2024 23:39:38] Stopping component OpenTelemetryClient
INFO:     [11-07-2024 23:39:38] Application shutdown complete.
INFO:     [11-07-2024 23:39:38] Finished server process [15865]
WARNING:  [11-07-2024 23:40:31] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:40:31] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:40:31] Starting component System
DEBUG:    [11-07-2024 23:40:31] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:40:31] Starting component SqliteDB
DEBUG:    [11-07-2024 23:40:31] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:40:31] Starting component Posthog
DEBUG:    [11-07-2024 23:40:31] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:40:31] Starting component SegmentAPI
INFO:     [11-07-2024 23:40:31] Started server process [16100]
INFO:     [11-07-2024 23:40:31] Waiting for application startup.
INFO:     [11-07-2024 23:40:31] Application startup complete.
INFO:     [11-07-2024 23:40:31] Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
WARNING:  [11-07-2024 23:40:50] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:40:50] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:40:50] Starting component System
DEBUG:    [11-07-2024 23:40:50] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:40:50] Starting component SqliteDB
DEBUG:    [11-07-2024 23:40:50] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:40:50] Starting component Posthog
DEBUG:    [11-07-2024 23:40:50] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:40:50] Starting component SegmentAPI
INFO:     [11-07-2024 23:40:50] Started server process [16123]
INFO:     [11-07-2024 23:40:50] Waiting for application startup.
INFO:     [11-07-2024 23:40:50] Application startup complete.
INFO:     [11-07-2024 23:40:50] Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
WARNING:  [11-07-2024 23:41:52] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [11-07-2024 23:41:52] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [11-07-2024 23:41:52] Starting component System
DEBUG:    [11-07-2024 23:41:52] Starting component OpenTelemetryClient
DEBUG:    [11-07-2024 23:41:52] Starting component SqliteDB
DEBUG:    [11-07-2024 23:41:52] Starting component QuotaEnforcer
DEBUG:    [11-07-2024 23:41:52] Starting component Posthog
DEBUG:    [11-07-2024 23:41:52] Starting component LocalSegmentManager
DEBUG:    [11-07-2024 23:41:52] Starting component SegmentAPI
INFO:     [11-07-2024 23:41:52] Started server process [16334]
INFO:     [11-07-2024 23:41:52] Waiting for application startup.
INFO:     [11-07-2024 23:41:52] Application startup complete.
INFO:     [11-07-2024 23:41:52] Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
WARNING:  [12-07-2024 17:20:54] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
INFO:     [12-07-2024 17:20:54] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG:    [12-07-2024 17:20:54] Starting component System
DEBUG:    [12-07-2024 17:20:54] Starting component OpenTelemetryClient
DEBUG:    [12-07-2024 17:20:54] Starting component SqliteDB
DEBUG:    [12-07-2024 17:20:54] Starting component QuotaEnforcer
DEBUG:    [12-07-2024 17:20:54] Starting component Posthog
DEBUG:    [12-07-2024 17:20:54] Starting component LocalSegmentManager
DEBUG:    [12-07-2024 17:20:54] Starting component SegmentAPI
INFO:     [12-07-2024 17:20:54] Started server process [25909]
INFO:     [12-07-2024 17:20:54] Waiting for application startup.
INFO:     [12-07-2024 17:20:54] Application startup complete.
INFO:     [12-07-2024 17:20:54] Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
